### ISSUE TITLE
Thank you for the plugin ❤️ 

### ISSUE THREAD

**Issue by dkarter** [B4mbus/nvim-headband#17]
Hi @B4mbus,

Sorry to hear that this plugin will no longer be maintained and even deleted from Github. :(
Thank you for the gentle notice!

Can you please share more about this decision? Are you using something different these days to serve the same purpose?

Either way, just wanted to say thank you!

-- Dorian

**Comment by B4mbus** [comment]
To be honest I thought no one is actually using the plugin, the code requires a little bit of maintenance (why maintain something that is not used?), especially the part that filters out certain buffertypes, filetypes, etc.

I am also slowly preparing to write another big plugin that requires a lot of attention and work, so I thought that since the plugin is basically useless (there are a lot more plugins like this out there, plus statusline plugins also offer winbar feature) and unused, then I'll just delete it.

But since I have a proof now that someone is actually using headband, then I'm revoking the decision and starting to fix things that I noticed are broken and refactoring the codebase a bit.

Thanks and cheers.
